apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  ports:
    - name: 'http-port'
      protocol: "TCP"
      port: 8080      #エンドポイントにアクセスがきたポート
      targetPort: 80  #コンテナに処理を渡すポート
  selector:
    app: sample-app