apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  # Kubernetes NodeのIP、ClusterIPで受け付けるPort番号
  externalIPs:
    # 利用可能なIPアドレスはノードの情報から確認することが可能
    - 192.168.0.4
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80 # 転送先のコンテナのPort番号
  selector:
    app: sample-app