apiVersion: v1
kind: Service
metadata:
  name: sample-service-topology
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  topologyKeys:
    - kubernetes.io/hostname # 第一優先度：「kubernetes.io/hostname」ラベルを持つノード上のPodに転送
    - "*" # 第二優先度：いずれかのPod「*」に対して転送